name = "Lax429075Proofs"
defaultTargets = ["Lax429075Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "c5ea00351c28e24afc9f0f84379aa41082b1188f"

[[require]]
name = "Lax429075"
path = "../concepts"

[[require]]
name = "Lax434930"
git = "https://github.com/EdouardBonnet/classical-complexity"
rev = "026a662d6c203952e4fc6c6023a3c1adf7f0bc3e"
subDir = "concepts"

[[require]]
name = "Lax554803"
git = "https://github.com/EdouardBonnet/p-complement"
rev = "289e82d4351fe8c710add0dcbffd0290f016994e"
subDir = "concepts"

[[lean_lib]]
name = "Lax429075Proofs"
